/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.EnemyToUI;

/**
 *
 * @author paula
 */
public class EnemyView extends javax.swing.JPanel {
    LootView lootView;
    DamageView damageView;
    
    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        initComponents();
        
        lootView = new LootView();
        damageView = new DamageView();
        pBotin.add(lootView);
        pPerdidas.add(damageView);
        
        repaint();
        revalidate();
    }
    
    void setEnemy (EnemyToUI eUI) {
        lEnemigo.setText(eUI.getName());
        lPFuego.setText(Float.toString(eUI.getAmmoPower()));
        lPDefensa.setText(Float.toString(eUI.getShieldPower()));
        lootView.setLoot(eUI.getLoot());
        damageView.setDamage(eUI.getDamage());
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lE = new javax.swing.JLabel();
        lPF = new javax.swing.JLabel();
        lPD = new javax.swing.JLabel();
        lEnemigo = new javax.swing.JLabel();
        lPFuego = new javax.swing.JLabel();
        lPDefensa = new javax.swing.JLabel();
        pBotin = new javax.swing.JPanel();
        pPerdidas = new javax.swing.JPanel();

        lE.setForeground(new java.awt.Color(255, 0, 0));
        lE.setText("Enemigo:");

        lPF.setText("Potencia de fuego:");

        lPD.setText("Potencia de defensa:");

        lEnemigo.setText("jLabel4");

        lPFuego.setText("jLabel5");

        lPDefensa.setText("jLabel6");

        pBotin.setBorder(javax.swing.BorderFactory.createTitledBorder("Botín"));

        pPerdidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Pérdidas"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBotin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lEnemigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lPFuego))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lPD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lPDefensa)))
                        .addGap(0, 179, Short.MAX_VALUE))
                    .addComponent(pPerdidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lE)
                    .addComponent(lEnemigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPF)
                    .addComponent(lPFuego))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPD)
                    .addComponent(lPDefensa))
                .addGap(18, 18, 18)
                .addComponent(pBotin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pPerdidas, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lE;
    private javax.swing.JLabel lEnemigo;
    private javax.swing.JLabel lPD;
    private javax.swing.JLabel lPDefensa;
    private javax.swing.JLabel lPF;
    private javax.swing.JLabel lPFuego;
    private javax.swing.JPanel pBotin;
    private javax.swing.JPanel pPerdidas;
    // End of variables declaration//GEN-END:variables
}
