/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.HangarToUI;
import deepspace.ShieldToUI;
import deepspace.WeaponToUI;
import java.util.ArrayList;
import java.awt.Component;

/**
 *
 * @author paula
 */
public class HangarView extends javax.swing.JPanel {
    private int nWeapons;
    private int nShields;
    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
        
        nWeapons = 0;
        nShields = 0;
    }
    
    void setHangar (HangarToUI hUI) {
        String espacio = "Hangar con " + Integer.toString(hUI.getMaxElements()) + " lugares.";
        
        pHangar_.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)),espacio));
        pHangar_.removeAll();
        
        ArrayList<WeaponToUI> wUI = hUI.getWeapons();
        ArrayList<ShieldToUI> sUI = hUI.getShieldBoosters();
        
        nWeapons = 0;
        nShields = 0;
        
        WeaponView weaponView;
        ShieldBoosterView shieldBoosterView;
        
        for (WeaponToUI w : wUI) {
            weaponView = new WeaponView();
            weaponView.setWeapon(w);
            nWeapons++;
            pHangar_.add(weaponView);
        }
        
        for (ShieldToUI s : sUI){
            shieldBoosterView = new ShieldBoosterView();
            shieldBoosterView.setShieldBooster(s);
            nShields++;
            pHangar_.add(shieldBoosterView);
        }
        
        repaint();
        revalidate();
    }
    
    void getSelectedItems (ArrayList<Integer> weapons, ArrayList<Integer> shields) {
        int i;
        
        weapons.clear();
        
        for (i=0; i<nWeapons; i++){
            Component c = pHangar_.getComponent(i);
            
            if (((WeaponView) c).isSelected())
                weapons.add(i);
        }
        
        shields.clear();
        
        for (i=0; i<nShields; i++){
            Component c = pHangar_.getComponent(nWeapons+i);
            
            if (((ShieldBoosterView) c).isSelected())
                shields.add(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pHangar_ = new javax.swing.JPanel();

        jScrollPane1.setViewportView(pHangar_);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pHangar_;
    // End of variables declaration//GEN-END:variables
}
