/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.LootToUI;

/**
 *
 * @author paula
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }
    
    void setLoot (LootToUI lUI) {
        lNSupplies.setText(Integer.toString(lUI.getnSupplies()));
        lNWeapons.setText(Integer.toString(lUI.getnWeapons()));
        lNShields.setText(Integer.toString(lUI.getnShields()));
        lNHangars.setText(Integer.toString(lUI.getnHangars()));
        lNMedals.setText(Integer.toString(lUI.getnMedals()));
        lT.setVisible(true);
        
        if (lUI.isSpaceCity())
            lT.setText("Ciudad Espacial");
        else if (lUI.isGetEfficient())
            lT.setText("Estación Eficiente");
        else
            lT.setVisible(false);
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNSu = new javax.swing.JLabel();
        lNW = new javax.swing.JLabel();
        lNSh = new javax.swing.JLabel();
        lNH = new javax.swing.JLabel();
        lNM = new javax.swing.JLabel();
        lT = new javax.swing.JLabel();
        lNSupplies = new javax.swing.JLabel();
        lNWeapons = new javax.swing.JLabel();
        lNShields = new javax.swing.JLabel();
        lNHangars = new javax.swing.JLabel();
        lNMedals = new javax.swing.JLabel();

        lNSu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNSu.setText("nSupplies:");

        lNW.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNW.setText("nWeapons:");

        lNSh.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNSh.setText("nShields:");

        lNH.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNH.setText("nHangars:");

        lNM.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNM.setText("nMedals:");

        lT.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lT.setText("Transf:");

        lNSupplies.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNSupplies.setText("jLabel7");

        lNWeapons.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNWeapons.setText("jLabel8");

        lNShields.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNShields.setText("jLabel9");

        lNHangars.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNHangars.setText("jLabel10");

        lNMedals.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNMedals.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNSu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lNSupplies))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNSh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNShields))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNWeapons)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNHangars))
                    .addComponent(lT)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNMedals)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNSu)
                    .addComponent(lNH)
                    .addComponent(lNSupplies)
                    .addComponent(lNHangars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNW)
                    .addComponent(lNWeapons)
                    .addComponent(lNM)
                    .addComponent(lNMedals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNSh)
                    .addComponent(lNShields)
                    .addComponent(lT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lNH;
    private javax.swing.JLabel lNHangars;
    private javax.swing.JLabel lNM;
    private javax.swing.JLabel lNMedals;
    private javax.swing.JLabel lNSh;
    private javax.swing.JLabel lNShields;
    private javax.swing.JLabel lNSu;
    private javax.swing.JLabel lNSupplies;
    private javax.swing.JLabel lNW;
    private javax.swing.JLabel lNWeapons;
    private javax.swing.JLabel lT;
    // End of variables declaration//GEN-END:variables
}
