/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.ShieldToUI;

/**
 *
 * @author paula
 */
public class ShieldBoosterView extends javax.swing.JPanel {
    private boolean selected = false;
    
    /**
     * Creates new form ShieldBoosterView
     */
    public ShieldBoosterView() {
        initComponents();
        setOpaque (selected);
    }
    
    public boolean isSelected () {
        return selected;
    }
    
    void setShieldBooster (ShieldToUI sUI) {
        lPotencia.setText(Float.toString(sUI.getBoost()));
        lUsos.setText(Integer.toString(sUI.getUses()));
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lP = new javax.swing.JLabel();
        lPotencia = new javax.swing.JLabel();
        lU = new javax.swing.JLabel();
        lUsos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(182, 243, 240));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lP.setText("Potencia:");

        lPotencia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lPotencia.setText("jLabel3");

        lU.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lU.setText("Usos:");

        lUsos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lUsos.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPotencia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lUsos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lP)
                    .addComponent(lPotencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsos)
                    .addComponent(lU))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lP;
    private javax.swing.JLabel lPotencia;
    private javax.swing.JLabel lU;
    private javax.swing.JLabel lUsos;
    // End of variables declaration//GEN-END:variables
}
