/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;
import deepspace.WeaponToUI;

/**
 *
 * @author paula
 */
public class WeaponView extends javax.swing.JPanel {
    private boolean selected = false;
    
    /**
     * Creates new form WeaponView
     */
    public WeaponView() {
        initComponents();
        setOpaque(selected);
    }
    
    public boolean isSelected (){
        return selected;
    }
    
    void setWeapon (WeaponToUI wUI) {
        String titulo = wUI.getType().toString();
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), titulo));
        lTipo.setText(wUI.getType().toString());
        lPotencia.setText(Float.toString(wUI.getPower()));
        lUsos.setText(Integer.toString(wUI.getUses()));
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lT = new javax.swing.JLabel();
        lP = new javax.swing.JLabel();
        lU = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        lPotencia = new javax.swing.JLabel();
        lUsos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 251, 125));
        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lT.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lT.setText("Tipo:");

        lP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lP.setText("Potencia:");

        lU.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lU.setText("Usos:");

        lTipo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lTipo.setText("jLabel1");

        lPotencia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lPotencia.setText("jLabel2");

        lUsos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lUsos.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPotencia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lUsos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lT)
                    .addComponent(lTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPotencia)
                    .addComponent(lP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsos)
                    .addComponent(lU))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lP;
    private javax.swing.JLabel lPotencia;
    private javax.swing.JLabel lT;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lU;
    private javax.swing.JLabel lUsos;
    // End of variables declaration//GEN-END:variables
}
